apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: observability
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
      evaluation_interval: 15s

    scrape_configs:
      - job_name: "otel-collector"
        static_configs:
          - targets: ["otel-collector:8889"]

      - job_name: "prometheus"
        static_configs:
          - targets: ["localhost:9090"]

      - job_name: "grafana"
        static_configs:
          - targets: ["grafana:3000"]

      - job_name: "loki"
        static_configs:
          - targets: ["loki:3100"]



