services:
  otel-collector:
    image: otel/opentelemetry-collector:latest
    container_name: otel-collector
    volumes:
      - ./otel-collector-config.yaml:/etc/otel/config.yaml:ro
    command: ["--config", "/etc/otel/config.yaml"]
    ports:
      - "4317:4317" # OTLP gRPC
      - "55681:55681" # OTLP HTTP (se necessário)
      - "8889:8889" # Métricas para o Prometheus

  # Jaeger é um sistema de monitoramento de desempenho que coleta, armazena e exibe traces de aplicações.
  zipkin:
    image: openzipkin/zipkin:latest
    ports:
      - "9411:9411" # Porta do Zipkin

  # Prometheus é uma ferramenta de monitoramento de desempenho que coleta, armazena e exibe métricas de aplicações.
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
    ports:
      - "9090:9090"

  # Loki é um sistema de monitoramento de desempenho que coleta, armazena e exibe logs de aplicações.
  loki:
    image: grafana/loki:latest
    container_name: loki
    ports:
      - "3100:3100"
    command: ["-config.file=/etc/loki/local-config.yaml"]
    volumes:
      - ./loki-config.yaml:/etc/loki/local-config.yaml:ro

  # Promtail é um componente do Loki que coleta logs de aplicações e os envia para o Loki.
  promtail:
    image: grafana/promtail:latest
    container_name: promtail
    volumes:
      - /var/log:/var/log
      - ./promtail-config.yaml:/etc/promtail/config.yml
    command: -config.file=/etc/promtail/config.yml

  # Grafana é uma ferramenta de monitoramento de desempenho que coleta, armazena e exibe métricas de aplicações.
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana # Persistência dos dados do Grafana

volumes:
  grafana_data:
