apiVersion: v1
kind: ConfigMap
metadata:
  name: loki-config
  namespace: observability
# Configuração do Loki
data:
  loki-config.yaml: |
    auth_enabled: false

    server:
      http_listen_port: 3100
      grpc_listen_port: 9095

    common:
      path_prefix: /var/loki

    storage_config:
      boltdb_shipper:
        active_index_directory: /var/loki/index
        cache_location: /var/loki/cache
      filesystem:
        directory: /var/loki/chunks

    schema_config:
      configs:
        - from: 2025-02-12
          store: boltdb-shipper
          object_store: filesystem
          schema: v13
          index:
            prefix: index_
            period: 24h

    ingester:
      chunk_idle_period: 5m
      chunk_retain_period: 30s
      lifecycler:
        ring:
          kvstore:
            store: memberlist
          replication_factor: 1

    compactor:
      working_directory: /var/loki/compactor

    limits_config:
      allow_structured_metadata: false


