apiVersion: apps/v1
kind: Deployment
metadata:
  name: loki
  namespace: observability
spec:
  replicas: 1
  selector:
    matchLabels:
      app: loki
  template:
    metadata:
      labels:
        app: loki
    spec:
      initContainers:
        - name: fix-permissions
          image: busybox
          command: ["sh", "-c", "mkdir -p /var/loki/cache /var/loki/index /wal && chmod -R 777 /var/loki /wal"]
          volumeMounts:
            - name: loki-storage
              mountPath: /var/loki
              subPath: loki-config.yaml #Monta o arquivo de configuração do Loki
            - name: loki-storage
              mountPath: /wal

      containers:
        - name: loki
          image: grafana/loki:latest
          args: ["-config.file=/etc/loki/loki-config.yaml"]
          volumeMounts:
            - name: loki-config
              mountPath: /etc/loki/loki-config.yaml
              subPath: loki-config.yaml #Monta o arquivo de configuração do Loki
            - name: loki-storage
              mountPath: /var/loki
            - name: loki-storage
              mountPath: /wal 
          resources:
            requests:
              memory: "48Mi"
              cpu: "40m"
            limits:
              memory: "96Mi"
              cpu: "80m"
      volumes:
        - name: loki-config
          configMap:
            name: loki-config
        - name: loki-storage
          persistentVolumeClaim:
            claimName: loki-pvc


