apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-config
data:
  grafana.ini: |
    [server]
    domain = localhost
    http_port = 3000
    root_url = %(protocol)s://%(domain)s/

    [database]
    type = sqlite3
    path = /var/lib/grafana/grafana.db

    [auth.anonymous]
    enabled = true
