#Apenas para desenvolvimento, em producao usa o pvc, pois dessa forma o 
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: standard  # Usa o storage padrão do cluster
