apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-config
  namespace: observability
data:
  grafana.ini: |
    [server]
    http_port = 3000
    domain = grafana.local
    root_url = %(protocol)s://%(domain)s:%(http_port)s/

    [security]
    admin_user = admin
    admin_password = admin  # ⚠️ Altere para uma senha segura em produção!

    [auth.anonymous]
    enabled = true  # Permite acesso anônimo (caso necessário)

    [auth]
    disable_login_form = false  # Mantém o login ativo

    [users]
    allow_sign_up = false  # Desativa novos cadastros

    [log]
    level = info
    mode = console

    [dashboards]
    default_home_dashboard_path = /var/lib/grafana/dashboards/home.json

